<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dineshma-Lt" failures="1" tests="3" name="FrameworkSeleniumFrameworkDesign.tests.ErrorValidation" time="35.526" errors="0" timestamp="2024-05-28T00:28:46 IST" skipped="1">
  <testcase classname="FrameworkSeleniumFrameworkDesign.tests.ErrorValidation" name="producterrorvalidation" time="11.787"/>
  <testcase classname="FrameworkSeleniumFrameworkDesign.tests.ErrorValidation" name="loginerrorvalidation" time="9.688">
    <skipped/>
  </testcase> <!-- loginerrorvalidation -->
  <testcase classname="FrameworkSeleniumFrameworkDesign.tests.ErrorValidation" name="loginerrorvalidation" time="14.051">
    <failure message="expected:&lt;Incorrect email[s] or password.&gt; but was:&lt;Incorrect email[] or password.&gt;" type="junit.framework.ComparisonFailure">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Incorrect email[s] or password.> but was:<Incorrect email[] or password.>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.Assert.assertEquals(Assert.java:107)
at FrameworkSeleniumFrameworkDesign.tests.ErrorValidation.loginerrorvalidation(ErrorValidation.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- loginerrorvalidation -->
</testsuite> <!-- FrameworkSeleniumFrameworkDesign.tests.ErrorValidation -->
